# Generated by Django 2.1.3 on 2018-11-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals_app', '0002_auto_20181119_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='cleavage',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='color',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='crystal_habit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='crystal_symmetry',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='crystal_system',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='diaphaneity',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='formula',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='image_caption',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='luster',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='mohs_scale_hardness',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='optical_properties',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='refractive_index',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='specific_gravity',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='streak',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='strunz_classification',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mineral',
            name='unit_cell',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='image_filename',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
