# Generated by Django 2.1.3 on 2018-11-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals_app', '0003_auto_20181119_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='group',
            field=models.TextField(default=''),
        ),
    ]
